### ISSUE TITLE
Hlo I'm Vinay. I had some problem in project can you please explain about it.

### ISSUE THREAD

**Issue by vinaydugyala** [samanvitha-125/markdown-portfolio#6]

**Comment by samanvitha-125** [comment]
Hi, Vinay ! yes i can explain about it please explain the issue.

**Comment by vinaydugyala** [comment]
During project explanation i was not attended on that day can you please tell how to do it.

**Comment by vinaydugyala** [comment]
actually i had minimal knowledge on coading. i'm from embedded background. Can you please explain in detail about it.

**Comment by samanvitha-125** [comment]
you have those meetings accessable right ? if you want to know what sir said,visit the meet recordings. i am not so good in it to explain..!

**Comment by vinaydugyala** [comment]
I Don't know about .c and .h files can you tell about them.

**Comment by samanvitha-125** [comment]
.c files are basically written to decrease the complexity and length of the files. For example, if you have some 2000 to 3000 lines of code to understand it better you would write itinto multiple files.   .h files are header files, to include the headers you declare them in seperate file

**Comment by vinaydugyala** [comment]
how to create them.How can we relate from one file to another file like .c or .h files.

**Comment by vinaydugyala** [comment]
sorry but i don't have much knowledge about it.

**Comment by vinaydugyala** [comment]
can you please explain about it.

**Comment by vinaydugyala** [comment]
is code are avaliable in internet.can u suggest please.

**Comment by samanvitha-125** [comment]
https://www.interviewbit.com/blog/c-projects/?amp=1
